### ISSUE TITLE
Replaces text - yet removes all formatting, embedded pictures, etc

### ISSUE THREAD

**Issue by 5k3105** [legion-zver/go-docx-templates#1]
Hi,

I had no luck just replacing text with ```github.com/nguyenthenguyen/docx``` so tried with your library.

It does replace the text but reformats the word doc, removing pictures, columns, and other formatting.

Is this by design? Is there a way to replace text markers only?

Thanks.

```go
package main

import (
	"github.com/legion-zver/go-docx-templates"
)

type TestStruct struct {
    Heading string
    Campaignid string
    Gps string
}

func main() {
	
   template, err := docxt.OpenTemplate("./DailyReportTemplate1.docx")
    if err != nil {
        println(err)
        return
    }  

	test := new(TestStruct)
	test.Heading = "2017_P1C1 Daily Report"
	test.Campaignid = "2017_P1C1"
	test.Gps = "01 - TALL, 01 - TOOL"
	
    if err := template.RenderTemplate(test); err != nil {
        println(err)
        return
    }
    if err := template.Save("result.docx"); err != nil {
        println(err)
        return
    }
	
	}
```

**Comment by bestplay** [comment]
Hi @5k3105 
Did you solved this issue?

**Comment by 5k3105** [comment]
Hi,

I used something like this ```https://github.com/sergey-chechaev/jpdocx``` and customized.

**Comment by bestplay** [comment]
@5k3105  I had try https://github.com/sergey-chechaev/jpdocx. 

But it don't hanle xml nodes, just replace the plain text. 

MS Word will split pattern text into different xml nodes in some situations.

Could you share your customized version?

Thank you very much
