### ISSUE TITLE
hyperlink in the template

### ISSUE THREAD

**Issue by poyomunandar** [legion-zver/go-docx-templates#7]
I have created hyperlink in the template but then it disappear in the new rendered document. Why does it happen?

**Comment by legion-zver** [comment]
@poyomunandar hi, i haven't supported this package in a while, but the problem with the Xml serial at Reading and preservation of docx, I did not describe the support of all types. (see decode/encode methods [https://github.com/legion-zver/go-docx-templates/blob/83e215e5caecdbd2ec412cff0f28ff4b7e7f53ce/docx/document.go#L54](https://github.com/legion-zver/go-docx-templates/blob/83e215e5caecdbd2ec412cff0f28ff4b7e7f53ce/docx/document.go#L54)
